module.exports = {
  someSidebar: {
    'SDK Resources': [
      'index',
      'contributing',
      'analytics',
      'env-var',
      'messaging',
      'native-form',
      'relay-id',
      'resolve-url',
      'yup',
      'exceptions',
    ],
    API: [
      'api/getting-started',
      'api/axios-resources',
      {
        type: 'category',
        label: 'Definitions',
        items: [
          'api/definitions/codes',
          'api/definitions/csv',
          'api/definitions/files',
          'api/definitions/logs',
          'api/definitions/navigation',
          'api/definitions/notifications',
          'api/definitions/organizations',
          'api/definitions/pdfs',
          'api/definitions/permissions',
          'api/definitions/providers',
          'api/definitions/regions',
          'api/definitions/settings',
          'api/definitions/spaces',
          'api/definitions/user-permissions',
          'api/definitions/users',
        ],
      },
      'api/authorizations',
      'api/downloads',
      'api/uploads',
    ],
    Recipes: ['recipes/proxy', 'recipes/httpRequest'],
  },
};
