module.exports = {
  someSidebar: {
    'SDK Resources': ['index', 'contributing'],
    API: [
      'api/getting-started',
      'api/axios-resources',
      {
        type: 'category',
        label: 'Definitions',
        items: [
          'api/definitions/codes',
          'api/definitions/csv',
          'api/definitions/files',
          'api/definitions/logs',
          'api/definitions/navigation',
          'api/definitions/notifications',
          'api/definitions/organizations',
          'api/definitions/pdfs',
          'api/definitions/permissions',
          'api/definitions/providers',
          'api/definitions/regions',
          'api/definitions/settings',
          'api/definitions/spaces',
          'api/definitions/user-permissions',
          'api/definitions/users',
        ],
      },
      'api/authorizations',
      'api/downloads',
      'api/uploads',
    ],
    Features: [
      'features/analytics',
      'features/env-var',
      'features/messaging',
      'features/native-form',
      'features/relay-id',
      'features/resolve-url',
      'features/yup',
      'features/exceptions',
    ],
    Recipes: ['recipes/proxy'],
  },
};
