extends: availity/browser
rules:
  unicorn/no-useless-undefined: 0
  unicorn/prefer-string-slice: 0
  prefer-arrow-callback: ['error', { allowNamedFunctions: true }]
  jest/no-deprecated-functions: 0
  jest/no-conditional-expect: 0
  jest/no-commented-out-tests: 0
globals:
  Buffer: false
  global: false
  process: false
  vi: false
settings:
  jest:
    version: 30
